env:
  node: true
  es6: true
  jest: true
extends: 'eslint:recommended'
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 2016
  requireConfigFile: false
  sourceType: module
rules:
  indent:
    - error
    - 2
    - {SwitchCase: 1}
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-console:
    - 1
